Repository match-gg/MATCH_FE_TS, pull requests merged in 2023-08, with the labels that each got.

#59 Feature/issue/57
  src/apis/api/firebase.ts
  src/components/Review.tsx
  src/components/card-actions/EditCardBtn.tsx
  src/components/card-actions/FinishBtn.tsx
  src/pages/battlegrounds/CardListContainer.tsx
  src/pages/battlegrounds/index.tsx
  src/pages/leagueoflegends/CardDetailContainer.tsx
  src/pages/leagueoflegends/CardListContainer.tsx
  src/pages/leagueoflegends/index.tsx
  src/pages/overwatch/CardDetailContainer.tsx
  src/pages/overwatch/CardListContainer.tsx
  src/pages/overwatch/index.tsx
Labels: enhancement

#72 Add information display and update function for each game
  src/apis/api/common.ts
  src/apis/api/pubg.ts
  src/apis/api/user.ts
  src/pages/battlegrounds/Card.tsx
  src/pages/battlegrounds/MemberSlot.tsx
  src/pages/mypage/GameInfo.tsx
  src/pages/mypage/Games.tsx
  src/pages/mypage/Games/AddGame.tsx
  src/pages/mypage/Games/LolInfo.tsx
  src/pages/mypage/Games/Nickname.tsx
  src/pages/mypage/Games/OverwatchInfo.tsx
  src/pages/mypage/Games/PubgInfo.tsx
  src/pages/mypage/MyInfo.tsx
  src/pages/mypage/UserInfoContainer.tsx
  src/pages/mypage/UserInfoFetcher.tsx
  src/pages/mypage/data.ts
  src/store/mypage-slice.ts
Labels: enhancement, feature

#71 Add firstRead in chat messages
  src/App.tsx
  src/apis/api/common.ts
  src/apis/api/firebase.ts
  src/apis/api/leagueoflegends.ts
  src/apis/api/overwatch.ts
  src/apis/api/pubg.ts
  src/apis/api/user.ts
  src/apis/utils/index.ts
  src/components/Review.tsx
  src/components/card-actions/JoinBtn.tsx
  src/components/card-actions/LeaveBtn.tsx
  src/components/chat/ChatRoom.tsx
  src/components/chat/JoinedParty.tsx
  src/components/header/UserMenu.tsx
  src/components/notification/ChatRoomListFetcher.tsx
  src/components/notification/NotiAccordion.tsx
  src/components/notification/Notification.tsx
  src/pages/battlegrounds/CardDetailFetcher.tsx
  src/pages/battlegrounds/CardListFetcher.tsx
  src/pages/battlegrounds/CreateCard.tsx
  src/pages/battlegrounds/EmptySlot.tsx
  src/pages/battlegrounds/MemberSlot.tsx
  src/pages/leagueoflegends/CardDetailFetcher.tsx
  src/pages/leagueoflegends/CardListFetcher.tsx
  src/pages/leagueoflegends/CreateCard.tsx
  src/pages/leagueoflegends/EmptySlot.tsx
  src/pages/leagueoflegends/MemberSlot.tsx
  src/pages/login/redirect.tsx
  src/pages/mypage/Games.tsx
  src/pages/mypage/Games/AddGame.tsx
  src/pages/mypage/Games/LolInfo.tsx
  src/pages/mypage/Games/Nickname.tsx
  src/pages/mypage/Games/OverwatchInfo.tsx
  src/pages/mypage/Games/PubgInfo.tsx
  src/pages/mypage/UserInfoFetcher.tsx
  src/pages/overwatch/CardDetailFetcher.tsx
  src/pages/overwatch/CardListContainer.tsx
  src/pages/overwatch/CardListFetcher.tsx
  src/pages/overwatch/CreateCard.tsx
  src/pages/overwatch/EmptySlot.tsx
  src/pages/overwatch/MemberSlot.tsx
  src/pages/register/InputLol.tsx
  src/pages/register/InputOverwatch.tsx
  src/pages/register/InputPubg.tsx
  src/pages/register/SetFavGame.tsx
  src/store/refresh-slice.ts
  src/types/chats.ts
Labels: enhancement, feature

#89 Feat: Add Carousel for follower`s cards
  src/components/CardListFetcher.tsx
  src/components/followersCard/FollowCardListContainer.tsx
  src/components/followersCard/FollowCardListFetcher.tsx
  src/components/followersCard/FollowersCard.tsx
  src/pages/battlegrounds/CardListContainer.tsx
  src/pages/battlegrounds/EmptySlot.tsx
  src/pages/battlegrounds/MemberSlot.tsx
  src/pages/battlegrounds/main.tsx
  src/pages/leagueoflegends/Card.tsx
  src/pages/leagueoflegends/CardListContainer.tsx
  src/pages/leagueoflegends/EmptySlot.tsx
  src/pages/leagueoflegends/MemberSlot.tsx
  src/pages/leagueoflegends/main.tsx
  src/pages/overwatch/Card.tsx
  src/pages/overwatch/CardListContainer.tsx
  src/pages/overwatch/EmptySlot.tsx
  src/pages/overwatch/MemberSlot.tsx
  src/pages/overwatch/main.tsx
  src/pages/register/Games.tsx
  src/store/card-slice.ts
Labels: feature

#91 Add evaluation information
  src/apis/api/user.ts
  src/pages/battlegrounds/MemberSlot.tsx
  src/pages/leagueoflegends/MemberSlot.tsx
  src/pages/overwatch/MemberSlot.tsx
Labels: feature

#92 [deploy] Add evaluation information
  src/apis/api/user.ts
  src/pages/battlegrounds/MemberSlot.tsx
  src/pages/leagueoflegends/MemberSlot.tsx
  src/pages/overwatch/MemberSlot.tsx
Labels: deploy

#94 refactoring mypage
  src/pages/mypage/Follow.tsx
  src/pages/mypage/Games.tsx
  src/pages/mypage/Games/AddGame.tsx
  src/pages/mypage/Games/LolInfo.tsx
  src/pages/mypage/Games/Nickname.tsx
  src/pages/mypage/Games/OverwatchInfo.tsx
  src/pages/mypage/Games/PubgInfo.tsx
  src/pages/mypage/MyInfo.tsx
  src/pages/mypage/UserInfoContainer.tsx
  src/pages/mypage/index.tsx
Labels: refactor
